---
- name: Installs azure-cli on a UNIX machine
  hosts: localhost
  become: true
  tasks:
    - name: Install Azure CLI
      community.general.homebrew:
        name: azure-cli
        state: present
