---
- name: Installs Go on a UNIX machine
  hosts: localhost
  become: true
  tasks:
    - name: Install Go (UNIX)
      community.general.homebrew:
        name: go
        state: present
      when: ansible_facts['os_family'] in ['Debian', 'Darwin']

    # add gvm to manage versions and remove the homebrew part
