---
- name: Installs homebrew on a UNIX machine
  hosts: localhost
  become: true
  tasks:
    # Ran into some weirdness with Docker where it puts bash in /usr/bin/bash which is not
    # where the homebrew installer expects it
    - name: Check bash location
      ansible.builtin.command: which bash
      register: bash_location
      changed_when: false

    - name: Install homebrew (Linux)
      ansible.builtin.shell:
        cmd: "/bin/bash -c '$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)'"
        creates: "/home/linuxbrew/.linuxbrew/bin/brew"
      when: ansible_facts['os_family'] == 'Debian' and bash_location == '/bin/bash'

    - name: Install homebrew (Docker)
      community.general.homebrew:
        name: "brew"
        state: present
      when: ansible_facts['os_family'] == 'Debian' and bash_location != '/bin/bash'

    - name: Install Homebrew if not installed (macOS)
      ansible.builtin.shell:
        cmd: "/bin/bash -c '$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)'"
        creates: /opt/homebrew/bin/brew
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Check if homebrew was installed successfully
      ansible.builtin.command: which homebrew
      register: homebrew_check
      changed_when: false

    - name: Fail playbook if homebrew installation fails
      ansible.builtin.fail:
        msg: "Homebrew installation failed"
      when: homebrew_check.stdout == ""
