---
- name: Preparing package manager for Linux config
  hosts: localhost
  become: true

  tasks:
    - name: Update apt cache (Linux)
      ansible.builtin.package:
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'
