---
# Whole playbook is unused because Python is installed during the init scripts
- name: Installs Python on a UNIX machine
  hosts: localhost
  become: true
  tasks:
    - name: Install Python and pip (Linux)
      ansible.builtin.package:
        name:
          - python3.12
          - python3-pip
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Python and pip (macOS)
      community.general.homebrew:
        name:
          - python@3.12
          - pip
        state: present
      when: ansible_facts['os_family'] == 'Darwin'
