---
- name: Installs CLI utils for macOS
  hosts: localhost
  become: true
  tasks:
    - name: Install tmux (Linux)
      ansible.builtin.package:
        name: tmux
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install tmux (macOS)
      community.general.homebrew:
        name: tmux
        state: present
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Check if .tmux.conf file exists
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.tmux.conf"
      register: tmux_conf_stat

    - name: Create .tmux.conf file if it doesn't exist
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.tmux.conf"
        state: touch
        mode: "0644"
      when: not tmux_conf_stat.stat.exists

    - name: Copy tmux.conf file
      ansible.builtin.copy:
        src: ./files/.tmux.conf
        dest: "{{ ansible_env.HOME }}/.tmux.conf"
        mode: "0644"
