---
- name: Installs Linux packages
  hosts: localhost
  become: true
  tasks:
    - name: Install zsh
      ansible.builtin.package:
        name: zsh
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Check if .zshrc file exists
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.zshrc"
      register: zshrc_stat

    - name: Create .zshrc file if it doesn't exist
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.zshrc"
        state: touch
        mode: "0644"
      when: not zshrc_stat.stat.exists
