---
- name: Clean up after a Linux configuration
  hosts: localhost
  tasks:
    - name: Clean up apt cache
      ansible.builtin.package:
        autoclean: true
        autoremove: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: Clean up homebrew
      community.general.homebrew:
        name: cleanup
      when: ansible_facts['os_family'] in ['Debian', 'Darwin']

    # Start shell services
    - name: Start skhd service
      anisble.builtin.shell:
        cmd: "skhd --start-service"
      args:
        executable: /bin/zsh

    - name: Start skhd service
      anisble.builtin.shell:
        cmd: "yabai --start-service"
      args:
        executable: /bin/zsh

    # Clean up the tmp folder?
