---
- name: Installs Linux packages
  hosts: localhost
  tasks:
    - name: Install CLI utils (Linux)
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - nano
        - git
        - fzf
        - jq
        - build-essential
        - htop
        - tree
        - gpg
      when: ansible_facts['os_family'] == 'Debian'
