---
- name: Installs VSCode on Linux
  hosts: localhost
  tasks:
    - name: Download VSCode .deb package
      ansible.builtin.get_url:
        url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
        dest: /tmp/vscode.deb
        mode: "0755"
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install VSCode package
      ansible.builtin.package:
        name: /tmp/vscode.deb
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Clean up downloaded VSCode package
      ansible.builtin.file:
        path: /tmp/vscode.deb
        state: absent
      when: ansible_facts['os_family'] == 'Debian'
