---
- name: Apply Linux configuration to a new machine
  hosts: localhost

- name: Install Linux utils
  ansible.builtin.import_playbook: docker_utils.yaml
- name: Install VSCode
  ansible.builtin.import_playbook: new_vscode.yaml
- name: Install Slack
  ansible.builtin.import_playbook: slack.yaml
