---
- name: Clean up after a Linux configuration
  hosts: localhost
  tasks:
    - name: Clean up apt cache
      ansible.builtin.package:
        autoclean: true
        autoremove: true

    - name: Clean up homebrew
      community.general.homebrew:
        name: cleanup

    # Clean up the tmp folder?
