---
# Whole playbook is unused because Python is installed during the init scripts
- name: Installs Python on a UNIX machine
  hosts: localhost
  tasks:
    - name: Install Python and pip (Linux)
      ansible.builtin.package:
        name:
          - python3.12
          - python3-pip
        state: present
