---
- name: Installs SDKMAN on Debian/Ubuntu
  hosts: localhost
  tasks:
    - name: Download SDKMan # noqa no-changed-when command-instead-of-module risky-shell-pipe
      ansible.builtin.shell: "curl -s 'https://get.sdkman.io' | bash"
      args:
        executable: /bin/bash

    - name: Install SDKMAN
      ansible.builtin.command:
        cmd: "source '{{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh'"
      changed_when: false

    - name: Get SDKMAN version
      ansible.builtin.command:
        cmd: "sdk version"
      register: sdkman_version
      changed_when: false

    - name: Show SDKMAN version
      ansible.builtin.debug:
        msg: "sdkman version is {{ sdkman_version.stdout }}"
