---
- name: Installs Slack on Linux
  hosts: localhost
  tasks:
    - name: Download Slack package for Ubuntu/Debian
      ansible.builtin.get_url:
        url: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.27.145-0.1.amd64.deb
        dest: /root/tmp/slack-desktop.deb
        mode: "0755"

    - name: Install Slack on Debian/Ubuntu
      ansible.builtin.package:
        name: /root/tmp/slack-desktop.deb
        state: present

    - name: Clean up downloaded Slack packages
      ansible.builtin.file:
        path: /root/tmp/slack-desktop.deb
        state: absent
