---
- name: Installs CLI utils for macOS
  hosts: localhost
  tasks:
    - name: Install tmux (Linux)
      ansible.builtin.package:
        name: tmux
        state: present

    - name: Check if .tmux.conf file exists
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.tmux.conf"
      register: tmux_conf_stat

    - name: Create .tmux.conf file if it doesn't exist
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.tmux.conf"
        state: touch
        mode: "0644"
      when: not tmux_conf_stat.stat.exists

    - name: Copy tmux.conf file (Docker)
      ansible.builtin.copy:
        src: /ansible/files/.tmux.conf
        dest: "{{ ansible_env.HOME }}/.tmux.conf"
        remote_src: true
        mode: "0644"
