---
- name: Apply macOS configuration to a new machine
  hosts: localhost

- name: Install macOS utils
  ansible.builtin.import_playbook: mac_utils.yaml
- name: Install macOS casks
  ansible.builtin.import_playbook: mac_casks.yaml
- name: Run cleanup
  ansible.builtin.import_playbook: post_tasks.yaml
