---
- name: Installs homebrew on a Linux machine
  hosts: localhost
  tasks:
    - name: Download Homebrew installation script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
        dest: /tmp/homebrew-install.sh
        mode: '0755'

    - name: Install Homebrew
      ansible.builtin.shell: |
        NONINTERACTIVE=1 /tmp/homebrew-install.sh
      args:
        creates: /home/linuxbrew/.linuxbrew/bin/brew
      environment:
        HOME: "{{ ansible_env.HOME }}"
        PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"

    - name: Add Homebrew to PATH
      ansible.builtin.lineinfile:
        path: /etc/profile.d/homebrew.sh
        create: true
        line: 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"'
        mode: '0644'

    - name: Update Homebrew
      community.general.homebrew:
        update_homebrew: true
      environment:
        PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"

    - name: Verify Homebrew installation
      environment:
        PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"
      block:
        - name: Check brew version
          ansible.builtin.command: brew --version
          register: brew_version
          changed_when: false  # Version check should never report as changed

        - name: Display Homebrew status
          ansible.builtin.debug:
            msg: "Brew version: {{ brew_version.stdout }}"

    - name: Fail playbook if homebrew installation fails
      ansible.builtin.fail:
        msg: "Could not verify homebrew installation"
      when: brew_version.stdout == ""
