---
- name: Run basic Linux admin tasks for a new Debian server
  hosts: localhost
  tasks:
    - name: Update apt cache
      ansible.builtin.package:
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: Create new sudo user account
      ansible.builtin.user:
        name: rickjhoppe
        state: present
        shell: /bin/bash
        password: { }
        home: '/Users/rickjhoppe'
        create_home: true

    - name: Give new user account sudo access
      ansible.builtin.user:
        name: rickjhoppe
        groups: sudo
        append: true

    - name: Disable root login via SSH
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"  # Disables root login via SSH
        state: present
        backup: true
      notify:
        - Restart SSH service to apply changes

    - name: Restart SSH service to apply changes
      ansible.builtin.service:
        name: sshd
        state: restarted
